title: mononn
author: mononn
email: tech@mononn.com
description: >- # this means to ignore newlines until "baseurl:"
  모난 기술 블로그
baseurl: "" # the subpath of your site, e.g. /blog
url: https://tech.mononn.com
favicon:
show_excerpts: false

# Build settings
theme: moving
plugins:
  - jekyll-feed

permalink: /:title/
timezone: Asia/Seoul

google_analytics: 'UA-156427940-1' # leave it blank if not wish

moving:
  avatar_url: "" # avatar in about page
  about_you: # short description about you in about page
  date_format: "%b %d" # date format of posts in home page
  back_to: "목록으로"

  # generate social links in about page.
  social_links:
    github: mononn
    rss: RSS
